name: Publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.96.0"
      - name: Build
        run: hugo -b https://jordydeweer.net -E
      - name: Deploy
          uses: sebastianpopp/ftp-action@releases/v2
          with:
            host: "jordydeweer.net"
            user: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            localDir: "public"
            remoteDir: "domains/jordydeweer.net/public_html"